# Generated by Django 4.0.6 on 2022-07-04 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanskrit', models.CharField(default='', max_length=100)),
                ('english_name', models.CharField(default='', max_length=100)),
                ('cues', models.TextField(default='')),
                ('image_url', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True)),
                ('user_string', models.CharField(default='PowerAsana', max_length=100)),
                ('intention', models.CharField(default='', max_length=200)),
                ('duration', models.DurationField()),
                ('intensity', models.CharField(default='', max_length=100)),
                ('peak_pose', models.CharField(default='', max_length=100)),
                ('pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='powerasana.pose')),
            ],
        ),
    ]
