# Generated by Django 4.0.6 on 2022-07-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerasana', '0003_rename_pose_sequence_poses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='poses',
        ),
        migrations.AddField(
            model_name='pose',
            name='sequences',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='powerasana.sequence'),
        ),
    ]
