# Generated by Django 4.0.6 on 2022-07-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerasana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='cues',
            field=models.TextField(default='Breathe'),
        ),
    ]
