# Generated by Django 4.0.6 on 2022-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerasana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='poses',
            field=models.ManyToManyField(to='powerasana.pose'),
        ),
    ]
