# Generated by Django 4.0.6 on 2022-07-13 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('powerasana', '0002_sequence_poses'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to=settings.AUTH_USER_MODEL),
        ),
    ]
