# Generated by Django 4.0.6 on 2022-07-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerasana', '0004_remove_sequence_poses_pose_sequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pose',
            name='sequences',
        ),
        migrations.AddField(
            model_name='sequence',
            name='poses',
            field=models.ManyToManyField(to='powerasana.pose'),
        ),
    ]
