# Generated by Django 4.0.6 on 2022-07-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerasana', '0004_remove_sequence_poses_pose_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='sequences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='powerasana.sequence'),
        ),
    ]
