# Generated by Django 4.0.6 on 2022-07-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerasana', '0005_remove_pose_sequences_sequence_poses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='poses',
        ),
    ]
