# Generated by Django 4.0.6 on 2022-07-17 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerasana', '0008_alter_sequence_poses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='cues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), size=3),
        ),
    ]
